# Base configuration for active learning experiments

dataset: "masonry"
dataset_type: "coco_instance"
data_dir: '/home3/vzcl68/Datasets/masonry-11/'
num_classes: 4  # Including background
img_size: 256


model_name: "maskrcnn"
pool: true
batch_size: 4
# Active learning parameters
initial_labeled: 0.2  # 10% initially labeled
query_size: 0.1        # Query 5 samples per cycle
al_cycles: 10         # 5 active learning cycles
epochs_per_cycle: 15  # Train for 15 epochs per cycle
initial_training_epoch: 10  # Initial training epochs
oracle_epochs: 50
cycle_epochs: 30
# Strategies
cold_start_strategy: "self_supervised"
use_rl: false
query_strategy: "uncertainty"
task: "instance_segmentation"

# Model parameters
use_cuda: true
lr: 0.005
momentum: 0.9
weight_decay: 0.0001
lr_steps: [30, 50]

# Logging
use_wandb: false
wandb_project: "AL_benchmark"
print_freq: 100

# Reinforcement Learning
policy_lr: 0.0003 
policy_hidden: 256
entropy_beta: 0.005
policy_temp_start: 1.5
policy_temp_end: 0.7
candidate_ratio: 0.4
dynamic_query_size: true

# Technical settings
num_workers: 4
seed: 42
checkpoint_dir: "results/checkpoints"
results_dir: "../results"